### PR TITLE
Interrupt safe {g|s}et_socket_active_status

### PR DESCRIPTION
**Pull request by davids5**
This fixes potential of ISR on get_socket_active_status and get_socket_active_status operations

### CODE REVIEW

**Comment by towynlin** [comment]
Building this change and programming it over DFU causes the following problem that does not occur with current spark master.  On the first reset after DFU programming, the Core cannot find the Cloud—it flashes red 3 times, then tries again and succeeds.

**Comment by davids5** [comment]
@towynlin This really need to be in the master or there will be FG:BG data inconstancy issues. Would you please give it another shot.

**Comment by towynlin** [comment]
Yup, works fine now.

**Comment by davids5** [comment]
Yeah!

**Pull request merged**
