### PR TITLE
Add intensity control for RGB led

### PR DESCRIPTION
**Pull request by mattande**
Please consider the following patch which adds intensity control for the RGB led. The default intensity is set at 1/4 off the peak power and can be modified by the user using either LED_SetIntensity() or RGB.intensity(). Values are set from 0 (off) to 255 (max). Intensity is taken into account for the LED_Fade / breathing LED.

To handle the color resolution during different levels of fade, the dynamic range of TIM1 has been increased 100x from 0-100 to 0-10000. The TIM1 interrupt remains at 100Hz.

These changes have been tested on hardware and look Ok to me. If you pull mattande/core-firmware:rgb_intensity (mattande/core-firmware@159ba033665d7e7a334949d8e6ad84f4d71fb121), application.cpp implements a short demo/test application which cycles through several user override color and fade at different intensity settings.

Note that changes in both core-firmware and core-common-lib are required for this change.

### CODE REVIEW

**Comment by carldanley** [comment]
Generally, I think this is a good idea however, I haven't had a chance to review code yet. That said, I think the method name should be `brightness` and not `intensity.`

**Comment by technobly** [comment]
First of all, great work @mattande!

+1 on `brightness` (is more common for light intensity)

Also a question, if you set RED to 0xFF and set BRIGHTNESS to 0xFF, will the resultant PWM be exactly 100%?  I kind of spent a bit seeing if I could answer this for myself...

Looking at the changes:
old TIM1_Autoreload is set to 99.
new TIM1_Autoreload is set to 9999.

old max PWM was limited to 39.2% of max value (99+1/255*100) 
new max PWM desired is 100%, so TIM1->CCR must reach 10000 (TIM1->ARR + 1)

Because of the scaling to generate the PWM, some bits are lost in the shuffle and the effective new PWM range is 0.01% to 99.22%.

If you change the 3 LED_TIM_CCR_SIGNAL[] lines:
`LED_TIM_CCR_SIGNAL[1] = (uint16_t)((((RGB_Color & 0xFF0000) >> 16) * LED_INTENSITY * (TIM1->ARR + 1)) >> 16);`
to this:
`LED_TIM_CCR_SIGNAL[1] = (uint16_t)(((((RGB_Color & 0xFF0000) >> 16) + 1) * (LED_INTENSITY + 1) * (TIM1->ARR + 1)) >> 16);`
you should see the PWM range equal 0 - 100% (TIM1->CCR1= 0.15 to 10000) ;-)

**Comment by towynlin** [comment]
OK, finally got around to testing this.  I'll probably bump up the default brightness a bit, but otherwise it looks good—thanks @mattande!  I also like the idea of changing the name from intensity to brightness, so after merging, I'll do that. Thanks @carldanley for weighing in on the name change—always good to have another pair of eyes. :eyes: :thumbsup: 

@technobly After I merge, If you could do some testing of the timer scaling to get the whole PWM range and issue a PR, that would really help me out.

Thank you all!

**Comment by satishgn** [comment]
Good Job @mattande https://github.com/mattande
Excited to see contributions from the community.

**Comment by towynlin** [comment]
Changed all names from intensity to brightness per discussion.

https://github.com/spark/core-common-lib/commit/2ae02efe3ea1cd0dcd49b6e011d57cb7a86c3679

https://github.com/spark/core-firmware/commit/16f9234eec5f66d67280c321b974c6741f3457d6

**Pull request merged**
