### PR TITLE
Use Mat McGowan's SPI bus arbitration code

### PR DESCRIPTION
**Pull request by towynlin**
Intended to solve issue https://github.com/spark/core-firmware/issues/233

See lengthy discussion in the Spark community:
https://community.spark.io/t/bug-bounty-ota-flash-reliability-issue/5438

### CODE REVIEW

**Comment by technobly** [comment]
I never tested this branch... and Andy's and Satish's branches were based on this one... which I did test with 100% success.  I was recommending Satish's core-common-lib bug-fix/ota-flash-reliability branch as it was the cleanest code and comments.  Can you comment on the difference between that and mdma's branch?

**Comment by towynlin** [comment]
Sure @technobly, thanks for asking!

Both branches solved the problem in all our internal testing. This code, to me, made more clear the actual problem and solution, but that's perhaps a matter of taste and background, since you thought the opposite.

Additionally, the software arbitration solves some problems that interrupt masking does not, as described by Mat here:
https://community.spark.io/t/bug-bounty-ota-flash-reliability-issue/5438/55?u=zachary

**Comment by technobly** [comment]
Ah... I guess I missed the part where Andy's code and MDMA's code were more significantly different... After looking at MDMA's posts again and his code I'm agreeing with you that it seems like a more natural fix.  I would like to test it though to make sure it works as well as Andy's interrupt masking, so I'll do that and report back after I collect enough data.

**Comment by technobly** [comment]
150 passed the dual curl script with 0 failures.  Since they all work the same for this test, it seems that it does then come down to the mutex with code vs. int masking argument.  The code mutex does seem to be easier to maintain if the system should change in the future.

**Pull request merged**
