### PR TITLE
Cleanup the sFLASH driver

### PR DESCRIPTION
**Pull request by mattande**
General cleanups to the sFLASH driver that fixes bugs in the existing driver if starting a write at an odd flash address and/or writing an odd number of bytes. There is also a modest improvement in code space utilization and slight speedup when writing > 4K bytes in a single write.

Test routines are available on mattande/core-firmware@4521ec1bd5bab6a5d1e236d84277c5004e83c5a2
- Expose only sFLASH_WriteBuffer(), sFLASH_ReadBuffer, sFLASH_Init,
  sFLASH_EraseSector() and sFLASH_EraseBulk() as these are the only
  functions external users should be calling.
- Add extern for binding in C++
- Note that there is no restriction on using auto address increment
  when the address crosses multiple pages
- Rewrite sFLASH_WriteBuffer() to correctly handle writing odd
  number of bytes and/or starting on an odd address

### CODE REVIEW

**Comment by mattande** [comment]
Found + fixed a problem, updated test cases that cover all branches are here: mattande/core-firmware@877ac95a1a431e4988e2e3be207a6197cb10e6fe

**Comment by mattande** [comment]
Increase the SPI clock to 18MHz when the sflash is selected. This shows approximately a 20% improvement in read and write speed when the proper auto-increment writes and block reads are used.

The SPI already used different configuration when selecting the CC3000 vs the sst25vf. This change only modifies the sst25vf SPI configuration clock divider to make it the minimum value, APB1 clock / 2. The slowest sst25vf part can handle max 25MHz SPI clock.

Updated test routines are here: mattande/core-firmware@96fca6829c30ab5f9270923b2394379a16b050ce

Previous times for writing a copy of the STM32's 128KB flash at 9MHz:

```
Erase 128KB in 453 ms.
Write 128KB in 1263 ms.
Read 128KB in 368 ms (128 byte blocks).
Verify sFlash read/write: pass
```

And at 18MHz:

```
Erase 128KB in 451 ms.
Write 128KB in 1048 ms.
Read 128KB in 304 ms (128 byte blocks).
Verify sFlash read/write: pass
```

**Comment by towynlin** [comment]
Winning. Very clean @mattande. Much appreciated.

**Comment by andyw-lala** [comment]
There is no reason I know of to use the slow spi for the CC3000 either, so
we should be able to crank it for both.

**Comment by mattande** [comment]
The CC3000's max SPI CLK is 16MHz.

**Comment by andyw-lala** [comment]
well, let's set them both to 16MHz. I can't believe the delta between 16
and 18 for the flash will matter _that_ much. certainloy getting out of the
1MHz penalty box will be the single best step we can take.

On Fri, Feb 14, 2014 at 12:58 PM, Matt Anderson notifications@github.comwrote:

> The CC3000's max SPI CLK is 16MHz.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/spark/core-common-lib/pull/6#issuecomment-35113386
> .

## 

Andy

**Comment by mattande** [comment]
Short version: You cant. The SPI2 clock is derived from the 36MHz APB1
clock, and the only options the hardware gives you are APB1 / 2 = 18MHz,
APB1 / 4 = 9MHz, APB1 / 8 = 4.5MHz, etc.

The SPI peripheral is not like the USART peripheral that gives you much
more flexibility to set its clock rate.

You might be be able to get a 16MHz clock by mucking with the APB1 or PCLK
up higher on the clock tree, but then may need a different external HF
crystal. And you are causing headaches for anyone else using peripherals on
APB1 or APB2 who assume a "normal" clock settings. Its not a good idea.

**Comment by andyw-lala** [comment]
Hmm, was reasonably sure I'd cranked it previously. Now I'm running it slow
because I'm hanging an analyzer off it to solve cfod.

**Pull request merged**
